Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Books> Book { get; set; }
    }
}

Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.Models
{
    public class Books
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Wprowadź tytuł książki!")]
        public string Nazwa { get; set; }
        [Required(ErrorMessage = "Wprowadź Imie i nazwisko autora!")]
        public string Autor { get; set; }
        [Required(ErrorMessage = "Wprowadź numer ISBN!"),StringLength(13)]
        public string ISBN { get; set; }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RazorPages.Models;

namespace RazorPages.Controllers
{
    [Route("api/Book")]
    [ApiController]
    public class BookController : Controller
    {
        

        private readonly ApplicationDbContext _db;

        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public async Task <IActionResult> GetAll()
        {
            return Json(new { data = await _db.Book.ToListAsync() });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var bookFromDb = await _db.Book.FirstOrDefaultAsync(u => u.ID == id);
            if (bookFromDb == null)
            {
                return Json(new { success = false, message = "Błąd podczas usuwania" });
            }
            _db.Book.Remove(bookFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Usuwanie zakończone" });
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Lista/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;

namespace RazorPages
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public Books Book { get; set; }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
               await _db.Book.AddAsync(Book);
               await _db.SaveChangesAsync();
               return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

Pages/Lista/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;

namespace RazorPages
{
    public class EditModel : PageModel
    {

        private readonly ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
            public Books Book { get; set; }
        public async Task OnGet(int id)
        {
            Book = await _db.Book.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
               var BookFromDb = await _db.Book.FindAsync(Book.ID);
                BookFromDb.Nazwa = Book.Nazwa;
                BookFromDb.Autor = Book.Autor;
                BookFromDb.ISBN = Book.ISBN;
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

Pages/Lista/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPages.Models;

namespace RazorPages
{
    public class IndexModel : PageModel
    {

        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Books> Book { get; set; }

        public async Task OnGet()
        {
            Book = await _db.Book.ToListAsync();
        }


        public async Task<IActionResult> OnPostDelete(int id)
        {
            var book = await _db.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            _db.Book.Remove(book);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

Pages/Lista/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages
{
    public class UpsertModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Test";
}

<div class="text-center">
    <h1 class="display-4">Test</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Lista/Create.cshtml
@page
@model RazorPages.CreateModel



<br />
<h2 class="text-info">Dodaj książkę</h2>
<br />

<div class=" border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Nazwa">Tytuł ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Nazwa" class="form-control" />
            </div>
            <span asp-validation-for="Book.Nazwa" class="text-danger"></span>
        </div>
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Autor">Autor ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Autor" class="form-control" />
            </div>
            <span asp-validation-for="Book.Autor" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="col-4">
                <label asp-for="Book.ISBN">Numer ISBN:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
            </div>
            <span asp-validation-for="Book.ISBN" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Dodaj" class="btn btn-success form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-primary form-control">Powrót do listy</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Lista/Edit.cshtml
@page
@model RazorPages.EditModel


<br />
<h2 class="text-info">Edytuj książkę</h2>
<br />

<div class=" border container" style="padding:30px;">
    <form method="post">
        <input type="hidden" asp-for="Book.ID" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Nazwa">Tytuł ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Nazwa" class="form-control" />
            </div>
            <span asp-validation-for="Book.Nazwa" class="text-danger"></span>
        </div>
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Autor">Autor ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Autor" class="form-control" />
            </div>
            <span asp-validation-for="Book.Autor" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="col-4">
                <label asp-for="Book.ISBN">Numer ISBN:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
            </div>
            <span asp-validation-for="Book.ISBN" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Edytuj" class="btn btn-success form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-primary form-control">Powrót do listy</a>
            </div>
        </div>

    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Lista/Index.cshtml
@page
@model RazorPages.IndexModel


<br />
<div class=" =container row p-0 m-0">
    <div class="col-9">
        <h2 class="text-dark">Lista Książek</h2>

    </div>
    <div class=" col-3">
        <a asp-page="Create" class="btn btn-success from-control text-white">Dodaj</a>

    </div>


    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Book.Count() > 0)
            {
                <table class=" table">
                    <tr class="thead-dark">
                        <th>
                            <label asp-for="Book.FirstOrDefault().Nazwa"></label>
                        </th>
                        <th>
                            <label asp-for="Book.FirstOrDefault().Autor"></label>
                        </th>
                        <th>
                            <label asp-for="Book.FirstOrDefault().ISBN"></label>
                        </th>
                        <th>

                    </tr>
                    @foreach (var item in Model.Book)
                    {
                        <tr>
                            <td>
                                @item.Nazwa

                            </td>
                            <td>
                                @item.Autor
                            </td>
                            <td>
                                @item.ISBN
                            </td>

                            <td>
                                <a asp-page="Edit" asp-route-id="@item.ID" type="button" class="btn btn-warning text-white">Edytuj</a>
                                <button asp-page-handler="Delete" asp-route-id="@item.ID" onclick="return confirm('Czy chcesz na stałe usunąć ten rekord?')" class="btn btn-danger">Usuń</button>

                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>Brak dostępnych książek</p>
            }
        </form>

    </div>


    <div class="col-12" style="text-align:center">
        <br />
        <span class="h3 text-info">DRUGA WERSJA</span>
        <br /><br />
    </div>
         



    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Autor</th>
                    <th>ISBN</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
    </div>
    @section Scripts{
        <script src="~/js/bookList.js"></script>
    }

Pages/Lista/Upsert.cshtml
@page
@model RazorPages.UpsertModel



<br />
<h2 class="text-info">Edytuj książkę</h2>
<br />

<div class=" border container" style="padding:30px;">
    <form method="post">
        <input type="hidden" asp-for="Book.ID" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Nazwa">Tytuł ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Nazwa" class="form-control" />
            </div>
            <span asp-validation-for="Book.Nazwa" class="text-danger"></span>
        </div>
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Book.Autor">Autor ksiązki:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Autor" class="form-control" />
            </div>
            <span asp-validation-for="Book.Autor" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="col-4">
                <label asp-for="Book.ISBN">Numer ISBN:</label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
            </div>
            <span asp-validation-for="Book.ISBN" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Edytuj" class="btn btn-success form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-primary form-control">Powrót do listy</a>
            </div>
        </div>

    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Lista/Index">Lista Książek</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>